# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: ansible-lint
        uses: ansible/ansible-lint-action@v4.1.0
        with:
          targets: "tasks/install.yml"
        
